name: Checks
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  checks:
    runs-on: ubuntu-latest
    name: OpenAPI definition
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run check
      uses: fluximus-prime/redocly-cli-github-action@v1
      with:
        args: lint openapi.yaml
