name: Publish API client derived from spec

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-ALPHA.[0-9]+"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "17"

      - id: get_version
        uses: battila7/get-version-action@v2.2.1

      - name: Generate the client
        env:
          TAG_VERSION: ${{ steps.get_version.outputs.version-without-v }}
        run: |
          echo "const version = \"$TAG_VERSION\";" > src/version.tsp
          npm install
          npm run build

      - name: Publish the client
        run: npm publish
        working-directory: ./dist/client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
