name: Publish API client derived from spec

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: OpenAPI Generator Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -i openapi.yaml -g typescript-fetch -o ./client"

      - run: cd client

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
